package utils

const (
	CPU_CORES_CPUINFO_ERROR  = -2
	LAVG_TREND_CPUINFO_ERROR = -1
	SUCCEEDED                = 0
	LAVG_TREND_ERROR         = 1
	LAVG_TREND_INCREASING    = 2
	LAVG_TREND_NORMAL        = 3
	FILE_EXT_ERR             = 4
	FILE_EXT_NOT_PROVIDED    = 5
	FILE_EXT_ASTERISK        = 6
	FILE_PREFIX_ERR          = 8
	FILE_PREFIX_ASTERISK     = 9
	DB_CONN_ERR              = 10
	DB_USERNAME_NOT_PROVIDED = 11
	DB_NAME_NOT_PROVIDED     = 12
	DB_HOSTNAME_NOT_PROVIDED = 14
	LAVG_LOAD_LEVEL_YELLOW   = 70
	DEL_FILE_LIST_E_SLEEP    = 60

	KEY_ENV  = "APP_ENV"
	APP_NAME = "scli"

	MODIFY_WALLPAPER_FILE_DOES_NOT_EXIST    = 2001
	MODIFY_WALLPAPER_ABS_FILEPATH_NOT_FOUND = 2002

	GENERATE_APPSECRET_ERROR_GETTING_RANDOM_BYTES                 = 3001
	GENERATE_APPSECRET_ERROR_CONVERTING_RANDOM_BYTES_TO_APPSECRET = 3002

	RANDOM_WALLPAPER_DEFAULT_CACHE_DIR = "~/.cache"

	AWS_REGION_DEFAULT                 = "ap-south-1"
	AWS_REGION_NOT_PROVIDED            = 6000
	AWS_ACCESS_KEY_NOT_PROVIDED        = 6001
	AWS_SECRET_ACCESS_KEY_NOT_PROVIDED = 6002
	AWS_INVALID_SERVICE_NAME           = 6003
	AWS_INVALID_APPLICATION_CLASS_NAME = 6004
	AWS_UNABLE_TO_CONNECT              = 6005
	AWS_INVALID_INSTANCE_ID            = 6006
	AWS_INVALID_TG_NAME                = 6007
	AWS_INVALID_ALB_ARN                = 6008
	AWS_INVALID_HOSTNAME               = 6009
	AWS_INVALID_TG_PORT                = 6010
	AWS_INVALID_RTG_PORT               = 6011
	RDS_ARN_NOT_PROVIDED               = 6012
	RDS_OT_NOT_PROVIDED                = 6013
	BUCKET_REGION_NOT_PROVIDED         = 6014
	BUCKET_NAME_NOT_PROVIDED           = 6015
	BUCKET_PREFIX_NOT_PROVIDED         = 6016

	HAPCONFIG_ERROR_GETTING_INSTANCES_DETAILS = 7001
	HAPCONFIG_INVALID_PORT_RANGE_START        = 7002
	HAPCONFIG_INVALID_PORT_RANGE_END          = 7003
	HAPCONFIG_INVALID_BACKEND_PORT            = 7004
	HAPCONFIG_INVALID_OUTFILE                 = 7005
)
